board/urls.py
from django.contrib import admin
from django.urls import path, include

import board
from board import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:board_id>/', views.detail, name="detail"),
    path('delete/<int:content_id>/', views.content_delete, name="delete"),
    path('update/<int:content_id>/', views.content_update, name="update"),
    path('content/create/<int:board_id>/', views.content_create, name="content_create"),
    path('create/', views.board_create, name = 'board_create'),
    path('content/<int:content_id>', views.content_detail, name = 'content_detail'),
    path('create/<int:content_id>', views.comment_create, name = 'comment_create'),
    path('update/<int:comment_id>', views.comment_update, name = 'comment_update'),
    path('delete/<int:comment_id>', views.comment_delete, name = 'comment_delete'),
    path('api/boards/', views.api_board_list)
]

board/models.py
from django.db import models
from django.db.models import CASCADE


class BoardList(models.Model):
    board_name = models.CharField(max_length=20, null=False)
    user_name = models.CharField(max_length=20, null=False)
    description = models.CharField(max_length=100, null=False)
    test = models.CharField(max_length=10)

    # def __str__(self):
    # return self.id


class Content(models.Model):
    board_id = models.ForeignKey(BoardList, on_delete=models.CASCADE, verbose_name="글", db_column='board_id')
    title = models.CharField(max_length=20, null=False)
    content = models.CharField(max_length=300, null=False)
    author = models.CharField(max_length=20, null=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title
    # views추가 예정


class Comments(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE, related_name='comment')
    body = models.CharField(max_length=300, null=False)
    author = models.CharField(max_length=20, null=False)
    date = models.DateField(auto_now_add=True)

board/forms.py
from django import forms

from board.models import BoardList, Content, Comments


class BoardCreationForm(forms.ModelForm):
    class Meta:
        model = BoardList
        fields = ['board_name','description']
        labels = {
            'board_name' : '게시판 이름',
            'description' : '게시판 설명'
        }
        widgets = {
            'board_name' : forms.TextInput(attrs={'class': 'form-control'}),
            'description' : forms.Textarea(attrs={'class': 'form-control', 'rows': 10})
        }


class ContentCreationForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = ['title','content']

class CommentCreationForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['body']

board/views.py
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

from board.forms import BoardCreationForm, ContentCreationForm, CommentCreationForm
from board.models import BoardList, Content, Comments
from board.serializers import BoardListSerializer


def index(request):
    board_list = BoardList.objects.all()

    context = {
        'board_list': board_list
    }
    # print(board_list)

    return render(request, 'board_list.html', context)


def board_create(request):
    if request.method == 'POST':
        form = BoardCreationForm(request.POST)
        if form.is_valid():
            board_info = form.save(commit=False)
            board_info.user_name = request.user.nickname
            board_info.save()
            return redirect('board:index')
        else:
            print(messages.error(request, 'Error!'))
    else:
        form = BoardCreationForm()
    return render(request, 'board_create.html', {'form': form})


# need to implement paging
def detail(request, board_id):

    content_list = Content.objects.filter(board_id=board_id)

    board_info = BoardList.objects.get(id=board_id)


    context = {
        'content_list': content_list,
        'board_id': board_id,
        'board_info':board_info
    }
    return render(request, 'board_detail.html', context)


# need to check valid
def content_create(request, board_id):
    print(request.user.nickname)
    bid = BoardList.objects.get(id=board_id)

    if request.method == 'POST':
        form = ContentCreationForm(request.POST)

        if form.is_valid():
            board_content = form.save(commit=False)
            board_content.author = request.user.nickname
            board_content.board_id_id = bid.id
            board_content.save()

            return redirect('board:detail', board_id)
        # content_info =
    return render(request, 'board_content_create.html', {'bid': bid})


def content_delete(request, content_id):
    delete_content = Content.objects.get(id=content_id)
    delete_content.delete()
    return redirect('board:index')


def content_update(request, content_id):
    base_content = Content.objects.get(id=content_id)
    bid = base_content.board_id_id
    if request.method == 'POST':
        update_form = ContentCreationForm(request.POST)
        if update_form.is_valid():
            base_content.title = request.POST['title']
            base_content.content = request.POST['content']
            base_content.save()
            return redirect('board:detail', base_content.board_id_id)
    context = {
        'content': base_content
    }

    return render(request, 'board_content_update.html', context)


def content_detail(request,content_id):
    content = get_object_or_404(Content,pk=content_id)
    comment = Comments.objects.filter(content_id = content_id)
    context = {
        'content':content,
        'comment':comment
    }
    return render(request, 'content_detail.html', context)


def comment_create(request, content_id):
    if request.method == 'POST':
        print('this is post')
        comment_form = CommentCreationForm(request.POST)
        if comment_form.is_valid():
            messages.add_message(
                request,
                messages.SUCCESS,
                '성공적으로 회원가입 완료'
            )
            comment_info = comment_form.save(commit=False)
            comment_info.author = request.user.nickname
            comment_info.content_id = content_id
            comment_info.save()
        return redirect('board:content_detail', content_id)

    return redirect('board:content_detail', content_id)

def comment_update(request, comment_id):
    comment_info = get_object_or_404(Comments, pk=comment_id)
    if request.method == "POST":
        update_form = CommentCreationForm(request.POST)
        if update_form.is_valid():
            content_id = comment_info.content_id

            comment_info.body = request.POST['body']
            comment_info.save()
            return redirect('board:content_detail', content_id)
    context = {
        'comment_id': comment_id,
        'body': comment_info.body
    }
    return render(request, 'comment_update.html', context)

def comment_delete(request, comment_id):
    delete_comment = Comments.objects.get(id=comment_id)
    content_id = delete_comment.content_id
    delete_comment.delete()
    return redirect('board:content_detail', content_id)

@api_view(['GET','POST'])
def api_board_list(request):
    if request.method == 'GET':
        query_set = BoardList.objects.all()
        board_list = BoardListSerializer(query_set, many=True) # json형태로 변환
        return Response(board_list.data)

    if request.method == 'POST':
        serializer = BoardListSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

board/templates/board_content_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="{% url 'board:content_create' a.id %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">제목</label>
          <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="제목" name="title">
        </div>
        <div class="mb-3">
          <label for="exampleFormControlTextarea1" class="form-label">내용</label>
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" name="content" placeholder="내용"></textarea>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-3">Confirm identity</button>
        </div>
    </form>
</div>
{% endblock %}

board/templates/board_content_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="{% url 'board:update' content.id %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">제목</label>
          <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="제목" name="title" value="{{content.title}}">
        </div>
        <div class="mb-3">
          <label for="exampleFormControlTextarea1" class="form-label">내용</label>
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" name="content" placeholder="내용">{{content.content}}</textarea>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-3">Confirm identity</button>
        </div>
    </form>
</div>
{% endblock %}

board/templates/board_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-12">
     <h5 class="my-3 border-bottom pb-2">게시판 생성</h5>
    <form method="post">
    {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}


    <div class="form-group">
            <label class="form-label">게시판 제목</label>
            <input type="text" class="form-control" placeholder="자유게시판" name="board_name">
        </div>
        <div class="form-group mb-3 mt-3">
            <label class="form-label mt-6">게시판 설명</label>
            <textarea class="form-control" name="description"
                      rows="10"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
</form>
</div>
{% endblock %}

board/templates/board_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h2 style="text-align:center; margin: 20px 0">{{board_info.board_name}}</h2>
    {% if content_list %}
    {% for content in content_list %}
    <div class="card " style="width:60%; margin:0 auto">
      <div class="card-header ">
        <div style="display:flex;justify-content : space-between">
            <a href="{% url 'board:content_detail' content.id %}">{{content.title}}</a>
            {% if request.user.nickname == content.author %}
            <div>
                <a class="btn btn-danger btn-sm" href="{% url 'board:delete' content.id %}" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">
                    <i class="fas fa-trash-alt"></i>
                </a>
                <a class="btn btn-primary btn-sm" href="{% url 'board:update' content.id %}" role="button">
                    <i class="fas fa-pen"></i>
                </a>
            </div>

            {%endif%}
        </div>

      </div>
      <div class="card-body">

        <p class="card-text">{{content.content}}</p>
          <div style="display:flex; justify-content:space-between">
              <div style="display:flex">
              <span style="font-size:14px">{{content.date}}</span>&nbsp;&nbsp;&nbsp;&nbsp;
              <strong style="font-size:14px">{{content.author}}</strong>
          </div>
            <div  style="display:flex">
                <i class="far fa-comment"  style="margin-top:4px; margin-right:4px"></i>
          <span>{{content.comment.count}}</span>
            </div>
          </div>

      </div>
    </div>
    {% if forloop.last %}
     {% if user.is_authenticated %}

        <a class="btn btn-primary" href="{% url 'board:content_create' board_id %}" role="button" style="margin-top:16px">게시글 작성하기</a>


    {%endif %}

    {% endif %}
    {% endfor %}

    {% else %}
    <p>아직 작성된 글이 없급니다,</p>
    <a class="btn btn-primary" href="{% url 'board:content_create' board_id %}" role="button" style="margin-top:16px">게시글 작성하기</a>
    {% endif %}


</div>
{% endblock %}

board/templates/board_list.html
{% extends 'base.html' %}
{% block content %}
    {% if board_list %}
    {% for board_info in board_list %}
        <div class="container card border-light mb-3 mt-3"
             style="max-width: 40%; text-align:center;margin-top:20">
          <div class="card-header">
              <div style="display:flex; justify-content:space-between" >
                  <h5>{{board_info.board_name}}</h5>
                  <a href="{% url 'board:detail'  board_info.id %}" style="text-decoration: none;">> </a>
              </div>

          </div>
          <div class="card-body">
            <p class="card-text">{{board_info.description}}</p>
          </div>

        </div>
    {% endfor %}
    {% else %}
    <p>no</p>
    {% endif %}
<div class="container mb-3">
    <a class="btn btn-primary " href="{% url 'board:board_create' %}" role="button">게시판 생성하기</a>
</div>
{% endblock %}

board/templates/comment_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="{% url 'board:comment_update' comment_id %}" method="post">
        {% csrf_token %}

        <div class="mb-3">
          <label for="exampleFormControlTextarea1" class="form-label">내용</label>
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" name="body" placeholder="내용">{{body}}</textarea>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-3">Confirm identity</button>
        </div>
    </form>
</div>
{% endblock %}

board/templates/content_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container" style="width:40%">
    <div class="card " style=" margin:0 auto">
      <div class="card-header ">
        <div style="display:flex;justify-content : space-between">
            <span>{{content.title}}</span>
            {% if request.user.nickname == content.author %}
            <div>
                <a class="btn btn-danger btn-sm" href="{% url 'board:delete' content.id %} " onclick="return confirm('정말 삭제하시겠습니까?')">
                    <i class="fas fa-trash-alt"></i>
                </a>
                <a class="btn btn-primary btn-sm" href="{% url 'board:update' content.id %}" role="button">
                    <i class="fas fa-pen"></i>
                </a>
            </div>

            {%endif%}
        </div>

      </div>
      <div class="card-body">
        <p class="card-text">{{content.content}}</p>
          <div style="display:flex">
              <span style="font-size:14px">{{content.date}}</span>&nbsp;&nbsp;&nbsp;&nbsp;
              <strong style="font-size:14px">{{content.author}}</strong>
          </div>

      </div>
    </div>

    {% if comment %}
    <p style="margin-top: 20px">댓글</p>
    {% for comment in comment %}

    <div class="card " style=" margin:0 auto">
      <div class="card-header ">
        <div style="display:flex;justify-content : space-between">
            <span>{{comment.author}}</span>
            {% if request.user.nickname == comment.author %}
            <div>
                <a class="btn btn-danger btn-sm" href="{% url 'board:comment_delete' comment.id %}" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">
                    <i class="fas fa-trash-alt"></i>
                </a>
                <a class="btn btn-primary btn-sm" href="{% url 'board:comment_update' comment.id %}" role="button">
                    <i class="fas fa-pen"></i>
                </a>
            </div>

            {%endif%}
        </div>

      </div>
      <div class="card-body">
        <p class="card-text">{{comment.body}}</p>
          <div style="display:flex">
              <span style="font-size:14px">{{comment.date}}</span>&nbsp;&nbsp;&nbsp;&nbsp;
              <strong style="font-size:14px">{{comment.author}}</strong>
          </div>

      </div>
    </div>
    {% endfor %}
    {% else %}
    <p>등록된 댓글이 없습니다.</p>
    {% endif %}
     {% if user.is_authenticated %}
    <form method="post" action="{% url 'board:comment_create' content.id %}" style="margin:20px auto;">
        {% csrf_token %}
        <span>댓글 달기</span>
        <textarea class="form-control" name="body"
                      rows="5" ></textarea>
        <button type="submit" class="btn btn-primary mb-3" style="margin-top:16px">댓글 작성하기</button>
    </form>
    {%endif %}



</div>
{% endblock %}