accounts/urls.py
from django.contrib import admin

from django.urls import path, include

from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('profile/<int:uid>/',views.profile,name='profile'),
    path('profile/modifyNickname/<int:uid>/',views.modify_nickname,name='modify_nickname'),
    path('profile/modifyPassword/<int:uid>/',views.modify_password,name='modify_password'),
    path('profile/delete/<int:uid>/',views.delete_user,name='delete'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', views.loginUser, name='login')

]

board/urls.py
from django.contrib import admin
from django.urls import path, include

import board
from board import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:board_id>/', views.detail, name="detail"),
    path('delete/<int:content_id>/', views.content_delete, name="delete"),
    path('update/<int:content_id>/', views.content_update, name="update"),
    path('content/create/<int:board_id>/', views.content_create, name="content_create"),
    path('create/', views.board_create, name = 'board_create'),
    path('content/<int:content_id>', views.content_detail, name = 'content_detail'),
    path('create/<int:content_id>', views.comment_create, name = 'comment_create'),
    path('update/<int:comment_id>', views.comment_update, name = 'comment_update'),
    path('delete/<int:comment_id>', views.comment_delete, name = 'comment_delete'),
    path('api/boards/', views.api_board_list)
]

accounts/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, nickname, password):

        if not email:
            raise ValueError('must have user email')
        if not password:
            raise ValueError('must have user password')

        user = self.model(
            email=self.normalize_email(email),
            nickname=nickname,

        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nickname, password):

        if not email:
            raise ValueError('must have user email')
        if not password:
            raise ValueError('must have user password')

        user = self.create_user(
            email=self.normalize_email(email),
            nickname=nickname,
            password = password
        )
        user.is_admin = True
        user.is_superuser = True
        user.is_staff = True

        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    # for social login
    USER_TYPE_CHOICES = (
        ('django', 'Django'),
        ('github', 'Github'),
        ('gmail', 'Gmail')
    )

    objects = UserManager()

    email = models.EmailField(
        max_length=255,
        unique=True,
    )
    nickname = models.CharField(max_length=15, null=False, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nickname']

    def __str__(self):
        return self.email


# class UserManager(BaseUserManager):

# class User(AbstractUser):

accounts/forms.py
from django import forms

from accounts.models import User
from board.models import BoardList, Content


class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email','nickname', 'password']

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email','password']

accounts/views.py
from django.contrib.auth import login, authenticate
# from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from accounts.forms import SignUpForm, LoginForm
from accounts.models import User


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            nickname = form.cleaned_data.get('nickname')
            account = User.objects.create_user(
                email=email,
                password=password,
                nickname=nickname
            )
            account.save()

            return redirect('accounts:login')

    return render(request, 'signup.html')

# 구현한 거 : 등록된 유저가 없는경우, 비밀번호 틀린 경우 다르게 alert
def loginUser(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        try:
            User.objects.get(email=email)
        except:
            context = {
                'alert_flag': True, 'message': "등록된 email이 아닙니다."
            }
            return render(request, 'login.html', context)
        print('과연rew')
        user = authenticate(request, email=email, password=password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('board:index')
        else:
            context = {
                'alert_flag': True, 'email': email, 'message': "비밀번호가 일치하지 않습니다."
            }
            return render(request, 'login.html', context)
    return render(request, 'login.html')


def profile(request, uid):
    print(uid)
    return render(request, 'profile.html', {'uid': uid})


def modify_nickname(request, uid):
    if request.method == 'POST':
        user = User.objects.get(pk=uid)
        user.nickname = request.POST['nickname']
        user.save()
        return redirect('accounts:profile', uid)

    return render(request, 'modify_nickname.html', {'uid': uid})


def delete_user(request, uid):
    if request.method == 'POST':
        user = User.objects.get(pk=uid)
        cur_password = request.POST['password']
        if user.check_password(cur_password):
            user.delete()
            return redirect('board:index')
        return render(request, 'delete_user.html', {'alert_flag': True, 'uid': uid})
    return render(request, 'delete_user.html', {'uid': uid})


# todo : 메일로 비밀번호 초기화 시키기
def modify_password(request, uid):
    if request.method == 'POST':
        user = User.objects.get(pk=uid)
        cur_password = request.POST['password']
        print(user.check_password(cur_password))
        return redirect('accounts:profile', uid)
    return render(request, 'modify_password.html', {'uid': uid})

accounts/templates/delete_user.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-12">
    <h5 class="my-3 border-bottom pb-2">회원 탈퇴</h5>
    {% if alert_flag %}
    <script>alert("비밀번호가 일치하지 않습니다.")</script>
    {% endif %}
    <form method="post" action="{% url 'accounts:delete' uid %}">
    {% csrf_token %}
    <div class="form-group">
            <label class="form-label">email</label>
            <input class="form-control" type="text" value="{{request.user.email}}" aria-label="Disabled input example" disabled readonly>
        </div>
        <div class="form-group">
            <label class="form-label">nickname</label>
            <input type="TEXT" class="form-control" placeholder="input new nickname" name="password">
        </div>

        <button type="submit" class="btn btn-primary" onclick="return confirm('Are you sure?')">탈퇴하기</button>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
                    <div class="alert alert-danger">
                        <strong>{{ field.label }}</strong>
                        {{ error }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
        {% endif %}
</form>
</div>

{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-12">
    <h5 class="my-3 border-bottom pb-2">로그인</h5>
    {% if alert_flag %}
    <script>alert('{{message}}')</script>
    {% endif %}
    <form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}

    <div class="form-group">
            <label class="form-label">email</label>
            {%if email%}
            <input type="email" class="form-control" placeholder="ex)test@test.com" name="email" value="{{email}}">
            {% else %}
            <input type="email" class="form-control" placeholder="ex)test@test.com" name="email" value="">
            {%endif%}
        </div>
        <div class="form-group">
            <label class="form-label">password</label>
            <input type="password" class="form-control" placeholder="" name="password">
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>

</form>
</div>
{% endblock %}

accounts/templates/modify_nickname.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-12">
    <h5 class="my-3 border-bottom pb-2">회원 정보 수정</h5>
    <form method="post" action="{% url 'accounts:modify_nickname' uid %}">
    {% csrf_token %}
    <div class="form-group">
            <label class="form-label">email</label>
            <input class="form-control" type="text" value="{{request.user.email}}" aria-label="Disabled input example" disabled readonly>
        </div>
        <div class="form-group">
            <label class="form-label">nickname</label>
            <input type="TEXT" class="form-control" placeholder="input new nickname" name="nickname">
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
                    <div class="alert alert-danger">
                        <strong>{{ field.label }}</strong>
                        {{ error }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
        {% endif %}
</form>
</div>
{% endblock %}

accounts/templates/modify_password.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-12">
    <h5 class="my-3 border-bottom pb-2">비밀번호 변경</h5>
    <form method="post" action="{% url 'accounts:modify_password' uid %}">
    {% csrf_token %}
    <div class="form-group">
            <label class="form-label">email</label>
            <input class="form-control" type="text" value="{{request.user.email}}" aria-label="Disabled input example" disabled readonly>
        </div>
        <div class="form-group">
            <label class="form-label">current password</label>
            <input type="TEXT" class="form-control" placeholder="input new nickname" name="password">
        </div>

        <button type="submit" class="btn btn-primary">제출하기</button>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
                    <div class="alert alert-danger">
                        <strong>{{ field.label }}</strong>
                        {{ error }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
        {% endif %}
</form>
</div>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-12">
    <h5 class="my-3 border-bottom pb-2">회원 정보</h5>

    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <div class="fw-bold">Email</div>
          {{request.user.email}}
        </div>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <div class="fw-bold">nickname</div>
          {{request.user.nickname}}
        </div>
      </li>
    </ul>
    <div style="margin-top: 12px">
        <a class="btn btn-primary" href="{% url 'accounts:modify_nickname' uid %}" role="button">정보 수정하기</a>
        <a class="btn btn-primary" href="{% url 'accounts:modify_password' uid %}" role="button">비밀번호 변경하기</a>
        <a class="btn btn-danger" href="{% url 'accounts:delete' uid %}" role="button">회원 탈퇴하기</a>
    </div>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-12">
    <h5 class="my-3 border-bottom pb-2">회원가입</h5>
    <form method="post" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    <div class="form-group">
            <label class="form-label">email</label>
            <input type="email" class="form-control" placeholder="ex)test@test.com" name="email">
        </div>
        <div class="form-group">
            <label class="form-label">password</label>
            <input type="password" class="form-control" placeholder="" name="password">
        </div>

        <div class="form-group mb-3 mt-3">
            <label class="form-label mt-6">nickname</label>
            <textarea class="form-control" name="nickname"
                      rows="10"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li
                    {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
</form>
</div>
{% endblock %}