accounts/urls.py
from django.contrib import admin

from django.urls import path, include

from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('profile/<int:uid>/',views.profile,name='profile'),
    path('profile/modifyNickname/<int:uid>/',views.modify_nickname,name='modify_nickname'),
    path('profile/modifyPassword/<int:uid>/',views.modify_password,name='modify_password'),
    path('profile/delete/<int:uid>/',views.delete_user,name='delete'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', views.loginUser, name='login')

]

board/urls.py
from django.contrib import admin
from django.urls import path, include

import board
from board import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:board_id>/', views.detail, name="detail"),
    path('delete/<int:content_id>/', views.content_delete, name="delete"),
    path('update/<int:content_id>/', views.content_update, name="update"),
    path('content/create/<int:board_id>/', views.content_create, name="content_create"),
    path('create/', views.board_create, name = 'board_create'),
    path('content/<int:content_id>', views.content_detail, name = 'content_detail'),
    path('create/<int:content_id>', views.comment_create, name = 'comment_create'),
    path('update/<int:comment_id>', views.comment_update, name = 'comment_update'),
    path('delete/<int:comment_id>', views.comment_delete, name = 'comment_delete'),
    path('api/boards/', views.api_board_list)
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
</head>

<body>
<div style="text-align:center">
    {% include "nav.html" %}
</div>
{%block content%}

{%endblock%}
</body>
</html>

templates/forms_error.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'board:index' %}">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          {% if user.is_authenticated %}
          <div style="display:flex">
            <a class="nav-link"href=" {% url 'accounts:profile' user.id %}">{{user.nickname}}</a>
          <a class="nav-link" style="color:red" href=" {% url 'accounts:logout' %}" onclick="return confirm('정말 로그아웃 하시겠습니까?')">logout</a>
          </div>
          {% else %}
          <a class="nav-link"href="{% url 'accounts:login' %}">login</a>
          {% endif %}
        </li>

      </ul>

    </div>
  </div>
</nav>